### ISSUE TITLE
fragment bits representation questions in Figure 28, 29

### ISSUE THREAD

**Issue by eurekaeru** [boucadair/draft-ietf-dots-data-channel#2]
## Figure 28

1. "flags": {"more"}
```
                   "ipv4": {
                     "flags": {"more"}
                   }
```
would be
```
                   "ipv4": {
                     "flags": "more"
                   }
```
according to 
+--rw flags?                 bits
https://tools.ietf.org/html/rfc7951#section-6.5 The "bits" Type

2. "flags": {""}
Can it be used for representation of all bits are zero?

## Figure 29

3. "fragment"
```
                   "ipv6": {
                     "fragment"
                   }
```
is
```
                   "ipv6": {
                     "fragment": [null]
                   }
```
according to
+--rw fragment?             empty
https://tools.ietf.org/html/rfc7951#section-6.9 The "empty" Type

**Comment by boucadair** [comment]
(ccing Jon)

Please see inline.


De : __kaname__ [mailto:notifications@github.com]
Envoyé : samedi 14 juillet 2018 12:25
À : boucadair/draft-ietf-dots-data-channel
Cc : Subscribed
Objet : [boucadair/draft-ietf-dots-data-channel] flagment bits representation questions in Figure 28, 29 (#2)

Figure 28

  1.  "flags": {"more"}

                   "ipv4": {

                     "flags": {"more"}

                   }

would be

                   "ipv4": {

                     "flags": "more"

                   }

according to
+--rw flags? bits
https://tools.ietf.org/html/rfc7951#section-6.5 The "bits" Type

[Med] Fixed.

  1.  "flags": {""}
Can it be used for representation of all bits are zero?
[Med] I lost the context how we ended with that representation. Actually, the last fragment is identified by a non-null offset, but I don’t know how to express that with the current netmod-acl. Perhaps, we need to replace "flags": {""} with destination-ipv4-network.
Figure 29

  1.  "fragment"

                   "ipv6": {

                     "fragment"

                   }

is

                   "ipv6": {

                     "fragment": [null]

                   }

according to
+--rw fragment? empty
https://tools.ietf.org/html/rfc7951#section-6.9 The "empty" Type

[Med] Agree. Fixed

**Comment by mrdeep1** [comment]
2."flags": {""}
Can it be used for representation of all bits are zero?

As this for a "match", the text is not clear, but I read it as if a bit is defined, then that bit will get checked and if set (1), then the match component is valid.  That was easy.  What happens if the bit is not defined?
- are we matching a 0? - the original question.  I do think so.

It gets more complicated when looking at the TCP flags.  If "flags" : "syn fin" is set, then the match will get bypassed if urg or ecn happens to be set.  To me, a security weakness.  I would prefer to see a "flagsmask" and "flags" combo to be clear about what really happens when doing the match.

If we do not care about any of the bits, then we just do not include the "flags" in the JSON.

As we have re-introduced the "fragment" for IPv6 (as well as IPv4) as the IPv6 fragment header is not matched by a flow label, I am inclined to drop the "flags" : "more" alternative out of Appendix A and elsewhere and we have IPv4 "fragment" again.

**Comment by boucadair** [comment]
Re-,

Re-introducing fragment keyword for IPv4 is exactly the conclusion I came to as this simplifies handling of fragments.

Things may be simple even with flags but this requires the support of “operator” so that we can manipulate offset and so on. Unfortunately, I don’t think we can get those fixed in the netmod acl, hence my preference to reintroduce the “fragment” thing.

Cheers,
Med

De : mrdeep1 [mailto:notifications@github.com]
Envoyé : lundi 16 juillet 2018 15:11
À : boucadair/draft-ietf-dots-data-channel
Cc : BOUCADAIR Mohamed IMT/OLN; Comment
Objet : Re: [boucadair/draft-ietf-dots-data-channel] fragment bits representation questions in Figure 28, 29 (#2)


2."flags": {""}
Can it be used for representation of all bits are zero?

As this for a "match", the text is not clear, but I read it as if a bit is defined, then that bit will get checked and if set (1), then the match component is valid. That was easy. What happens if the bit is not defined?

  *   are we matching a 0? - the original question. I do think so.

It gets more complicated when looking at the TCP flags. If "flags" : "syn fin" is set, then the match will get bypassed if urg or ecn happens to be set. To me, a security weakness. I would prefer to see a "flagsmask" and "flags" combo to be clear about what really happens when doing the match.

If we do not care about any of the bits, then we just do not include the "flags" in the JSON.

As we have re-introduced the "fragment" for IPv6 (as well as IPv4) as the IPv6 fragment header is not matched by a flow label, I am inclined to drop the "flags" : "more" alternative out of Appendix A and elsewhere and we have IPv4 "fragment" again.

**Comment by mrdeep1** [comment]
Agreed

**Comment by eurekaeru** [comment]
I also prefer to re-introducing fragment.
When flowspec(https://tools.ietf.org/html/rfc5575) is assumed as one of mitigation technologies, having "fragment" independent with "TCP flags" is preferable for me.
Moreover, it could  deviate netmod acl but having "flagsmask" and "flags" combo would be better.
